# Makefile generated at Tue Aug  4 20:38:22 AEST 2020

CC = gcc
CFLAGS = -Wall -g

circmain:	circ1.o circ2.o circmain.o
	$(CC) $(CFLAGS) -o $@ circ1.o circ2.o circmain.o

circ1.o:	circ1.h circ1.c
circ2.o:	circ2.h circ2.c
circmain.o:	circ1.h circmain.c
